const express=require("express");const app=express();const PORT=process.env.PORT||3000;const API="https://v3.football.api-sports.io";const cache=new Map();app.use(express.static(__dirname));
function pct(v){if(v==null)return null;const n=parseFloat(String(v).replace("%",""));return Number.isFinite(n)?n:null}
async function api(e){const k=process.env.API_FOOTBALL_KEY;if(!k)throw Error("API_FOOTBALL_KEY is missing. Add it in Render.");const h=cache.get(e);if(h&&Date.now()-h.t<3600000)return h.d;const r=await fetch(API+e,{headers:{"x-apisports-key":k,Accept:"application/json"}}),d=await r.json();if(!r.ok||(d.errors&&Object.keys(d.errors).length))throw Error(JSON.stringify(d.errors||{status:r.status}));cache.set(e,{t:Date.now(),d});return d}
async function prediction(id){try{const d=await api(`/predictions?fixture=${id}`),p=d.response?.[0]?.predictions;if(!p)return null;return{winner:p.winner?.name||null,advice:p.advice||null,home:pct(p.percent?.home),draw:pct(p.percent?.draw),away:pct(p.percent?.away),underOver:p.under_over||null,goals:p.goals||null}}catch(_){return null}}
function result(f,id){if(f.goals.home==null||f.goals.away==null)return null;const home=f.teams.home.id===id;const gf=home?f.goals.home:f.goals.away,ga=home?f.goals.away:f.goals.home;return gf>ga?"W":gf===ga?"D":"L"}
function form(fs,id){return(fs.response||[]).filter(f=>f.fixture.status?.short==="FT").map(f=>result(f,id)).filter(Boolean).slice(0,5)}
function goals(fs,id){let gf=0,ga=0,n=0;for(const f of(fs.response||[]).filter(f=>f.fixture.status?.short==="FT").slice(0,5)){if(f.goals.home==null)continue;const home=f.teams.home.id===id;gf+=home?f.goals.home:f.goals.away;ga+=home?f.goals.away:f.goals.home;n++}return n?`${gf} scored, ${ga} conceded in last ${n}`:"No recent goal data"}
app.get("/api/matches",async(req,res)=>{try{const date=new Date().toISOString().slice(0,10),l=req.query.league,e=l?`/fixtures?league=${encodeURIComponent(l)}&season=2026&date=${date}`:`/fixtures?date=${date}`,d=await api(e),fs=(d.response||[]).slice(0,20),out=await Promise.all(fs.map(async f=>({id:f.fixture.id,date:f.fixture.date,time:new Date(f.fixture.date).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),status:f.fixture.status?.short,league:f.league.name,home:f.teams.home.name,away:f.teams.away.name,homeId:f.teams.home.id,awayId:f.teams.away.id,homeLogo:f.teams.home.logo,awayLogo:f.teams.away.logo,prediction:await prediction(f.fixture.id)})));res.json(out)}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/analyze",async(req,res)=>{try{const id=Number(req.query.fixture);if(!id)throw Error("Missing fixture id");const fd=await api(`/fixtures?id=${id}`),f=fd.response?.[0];if(!f)throw Error("Fixture not found");const hi=f.teams.home.id,ai=f.teams.away.id;const[h,a,hh]=await Promise.all([api(`/fixtures?team=${hi}&last=5`),api(`/fixtures?team=${ai}&last=5`),api(`/fixtures/headtohead?h2h=${hi}-${ai}&last=10`)]);const hf=form(h,hi),af=form(a,ai),done=(hh.response||[]).filter(x=>x.fixture.status?.short==="FT");let hw=0,dr=0,aw=0,btts=0;for(const x of done){const hg=x.goals.home,ag=x.goals.away;if(hg==null||ag==null)continue;const homeScore=x.teams.home.id===hi?hg:ag,awayScore=x.teams.home.id===hi?ag:hg;if(homeScore>awayScore)hw++;else if(homeScore===awayScore)dr++;else aw++;if(hg>0&&ag>0)btts++}const n=hw+dr+aw;res.json({home:{name:f.teams.home.name,formText:hf.join(" → ")||"No recent completed matches",goalsText:goals(h,hi)},away:{name:f.teams.away.name,formText:af.join(" → ")||"No recent completed matches",goalsText:goals(a,ai)},h2h:{summary:n?`${hw} home wins · ${dr} draws · ${aw} away wins from ${n} H2H matches`:"No completed H2H matches available",btts:n?`${btts}/${n} H2H matches (${Math.round(btts/n*100)}%) had both teams scoring`:"Not available"},correctScore:"Not provided by the API response; Caesar Predict does not invent one.",note:"Recent form, H2H and goal data are shown as supporting context. The API prediction percentages remain the prediction source."})}catch(e){res.status(500).json({error:e.message})}});
app.get("/health",(_,res)=>res.json({ok:true,service:"Caesar Predict V2.1",time:new Date().toISOString()}));app.listen(PORT,()=>console.log(`Caesar Predict V2 running on port ${PORT}`));